version: "3.9"

services:
  web:
    build: .
    env_file: .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:7000"
    container_name: iaptest
    volumes:
      - .:/iaptest
    ports:
      - "7000:7000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]